name: flutter_dowith
description: Co-Work Todo Project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  calendar_timeline: ^1.1.1
  cloud_firestore: ^4.4.4
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.2.2
  firebase_core: ^2.7.1
  firebase_messaging: ^14.4.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^8.2.0
  flutter_riverpod: ^2.3.0
  font_awesome_flutter: ^10.4.0
  google_sign_in: ^6.0.2
  http: ^0.13.5
  intl: ^0.18.0
  line_icons: ^2.0.1
  path: ^1.8.2
  path_provider: ^2.0.13
  shared_preferences: ^2.0.18
  sqflite: ^2.2.5
  table_calendar: ^3.0.9
  uuid: ^3.0.7
  workmanager: ^0.5.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/icons/google_logo.png

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
