// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8qGfJPJr37aQSiktlhT35JkzCvMIGnsQ',
    appId: '1:286159962420:android:310150b3bbc3d5491be561',
    messagingSenderId: '286159962420',
    projectId: 'fir-db-af07e',
    databaseURL: 'https://fir-db-af07e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-db-af07e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-jq9dmMaJWwxNJRcKHvTCMHFL_oJsW_Y',
    appId: '1:286159962420:ios:33a812ba9d4f8d251be561',
    messagingSenderId: '286159962420',
    projectId: 'fir-db-af07e',
    databaseURL: 'https://fir-db-af07e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-db-af07e.appspot.com',
    iosClientId: '286159962420-muqpf1urpanl1eqlchgoso191b9cqp3c.apps.googleusercontent.com',
    iosBundleId: 'com.dowithdev.flutterDowith',
  );
}
